apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats-helm-release
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: nats-repo
      sourceRef:
        kind: HelmRepository
        name: nats-repo
        namespace: flux-system
      version: ">=0.8.0"
  releaseName: my-nats
  targetNamespace: default
  install:
    crds: Create
  upgrade:
    crds: CreateReplace