apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo-rollouts-repo
        namespace: flux-system
      version: ">=1.0.1"